sudo: required
services:
  - docker

before_install:
  - docker build -t eslam1146/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eslam1146/client-test npm test -- --watchAll=false

after_success:
  - docker build -t eslam1146/multi-client ./client
  - docker build -t eslam1146/multi-api ./api
  - docker build -t eslam1146/multi-worker ./worker
  - docker build -t eslam1146/multi-nginx ./nginx
  # Log into the docker-cli
  